#!/bin/sh

file="$HOME/.local/share/TODO"
n=$(tail -n 1 $file)
max=$(wc -l $file | awk '{print $1}')

case $BLOCK_BUTTON in
	1) sed '$ d' $file | xargs -0 notify-send
		;;
	2) st -e "$EDITOR" $0
		;;
	3) st -e "$EDITOR" $file
		;;
	4)
		[ "$n" -gt 1 ] && sed -i '$ s/.*/'"$(($n - 1))"'/' $file && pkill -RTMIN+7 dwmblocks
			;;
	5)
		[ "$n" -lt "$(($max - 1))" ] && sed -i '$ s/.*/'"$(($n + 1))"'/' $file && pkill -RTMIN+7 dwmblocks
			;;
esac

n=$(tail -n 1 $file)
msg="$(sed -n ''"$n"','"$n"'p' $file)"
[ ${#msg} -lt 30 ] && echo $msg || echo "$(echo  $msg | cut -c 1-27)""..."
