#!/bin/sh

case $BLOCK_BUTTON in
	1) curl --no-progress-meter wttr.in/gremsdorf | sed -n '3,7p' | sed 's/\[\([0-9]\+\|[0-9]\+;[0-9]\+;[0-9]\+\|\|[0-9]\+;[0-9]\+;[0-9]\+;[0-9]\+\)m//g' | xargs -0 notify-send
		;;
	2) st -e "$EDITOR" $0
		;;
	3) st -n "Wetter" -e wetter
		;;
esac

str=$(curl --no-progress-meter wttr.in/gremsdorf)
[ ${#str} -lt 60 ] && echo "Wetter-Server nicht verfügbar." && exit 1
curl --no-progress-meter wttr.in/hoechstadt | sed -n '3,4p' | sed 's/\[\([0-9]\+\|[0-9]\+;[0-9]\+;[0-9]\+\|\|[0-9]\+;[0-9]\+;[0-9]\+;[0-9]\+\)m//g' | cut -c 17- | sed ':a;N;$!ba;s/\n/, /g' | sed 's/\s\+/ /g' | cut -c 1-30
