#!/bin/bash

charge=$(acpi -b | grep -E -o '[0-9][0-9]?%')

if [ $charge = '00%' ]
then
	charge='FULL'
fi

remaining=$(acpi -b | grep -E -o '[0-9][0-9]?:[0-9][0-9]')
if [ $(acpi -b | awk '{print $3}') = "Charging," ]
then
	symbol=⚡
else
	symbol=🔋
fi

echo "$symbol $charge $remaining"
