#!/bin/bash

local_=$(timedatectl status | grep Local)
year=$(grep -E -o "[0-9][0-9][0-9][0-9]?\-" <<< $local_)
month=$(grep -E -o "?\-[0-9][0-9]?\-" <<< $local_)
day=$(grep -E -o "?\-[0-9][0-9]?\s" <<< $local_)

weekday=$(echo $local_ | awk '{print $3}')
date=$(echo $day$month$year | sed 's/^-//' | sed 's/-$//' | sed 's/ -/-/')
time_=$(grep -E -o "?\s[0-9][0-9]?:[0-9][0-9]" <<< $local_)

echo $weekday $date $time $time_
