#!/bin/bash

btstatus=$(echo -e "show" | bluetoothctl | grep "Powered")
echo $btstatus
if [ "$(echo $btstatus)" = "Powered: yes" ]
then
	notify-send "Turning Bluetooth off"
	echo -e "power off" | bluetoothctl
else
	notify-send "Turning Bluetooth on"
	echo -e "power on" | bluetoothctl
fi
