#!/bin/bash

pdb="$(grep pdb $1 | grep -E -o "\".*\"" | tr -d \")"
fn="${pdb:0:-3}"

gmx pdb2gmx -f $pdb -ff oplsaa -water none -ignh
gmx grompp -f /home/linkai/CC-PBSA/ccpbsa/parameters/min.mdp -maxwarn 1
gmx editconf -f topol.tpr -grasp -o $pdb
echo atom__res_radius_ > $fn"siz"
echo atom__resnumbc_charge_ > $fn"crg"
grep ATOM $pdb | awk '{printf "%-6s%-6s%-5s\n", $3, $4, $9}' >> $fn"siz"
grep ATOM $pdb | awk '{printf "%-6s%-3s%-7s%s\n", $3, $4, $5, $10}' >> $fn"crg"
sed -i 's/\s-/-/' $fn"crg"
delphi $1
