#!/bin/bash

youtube-dl -x --audio-format "mp3" -o "$HOME/ToRename/%(title)s.%(ext)s" "https://www.youtube.com/playlist?list=PLuN8omoxqHiOmm0G1UYfcn82NUuWezSlY"
cd /home/linkai/ToRename/
ls *.mp3 | while read -r line ; do echo "mv" $line  "<++>" $line ; done > renamelist.sh
vim renamelist.sh
bash renamelist.sh
picard *.mp3
mv *.mp3 $HOME/Musik
